pipeline {
    agent any
    stages {
        stage('compile') {
			steps {
                echo 'compiling..'
				git url: 'https://github.com/lerndevops/DevOpsClassCodes'
				bat label: '', script: 'mvn compile'
            }
        }
        stage('unit-test') {
			steps {
                echo 'codereview..'
				bat label: '', script: 'mvn test'
            }
			post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
			
        }
        stage('package') {
			steps {
                echo 'metric-check..'
				bat label: '', script: 'mvn package'	
            }
			
        }
    }
}
